server:
  port: 1101

spring:
  application:
    name: college-management-system

  datasource:
    url: jdbc:mysql://localhost:3306/college_db
    username: root
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
    ddl-auto: update
    show-sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000